apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sparrow-api
  name: sparrow-api
  namespace: sparrow-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparrow-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sparrow-api
    spec:
      containers:
      - image: sparrowprod.azurecr.io/sparrow-api:_BUILD__ID_
        name: sparrow-api
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80
        env:
          - name: WINDOWS_APP_SIGNATURE
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: WINDOWS_APP_SIGNATURE
          - name: WINDOWS_APP_URL
            valueFrom:
              secretKeyRef:
                name: sparrow-api-secret
                key: WINDOWS_APP_URL 
                
---

apiVersion: v1
kind: Service
metadata:
  name: sparrow-api
  labels:
    run: sparrow-api
  namespace: sparrow-test
spec:
  type: ClusterIP
  selector:
    app: sparrow-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
