name: Production
on:
  push:
    branches:
      - main

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@master
         - uses: richardrigutins/replace-in-files@v1
           with:
              files: "./deploymentManifests/deployment.yml"
              search-text: '_BUILD__ID_'
              replacement-text: '${{ github.run_number }}'

         - uses: azure/setup-kubectl@v2.0

         - uses: Azure/k8s-set-context@v2
           with:
              kubeconfig: ${{ secrets.KUBE_CONFIG }}

         - uses: Azure/k8s-deploy@v4
           with:
              action: deploy
              namespace: ${{ secrets.NAMESPACE }}
              manifests: |
                 ./deploymentManifests/deployment.yml
         - name: Apply Kubernetes Secret
           run: |
              cat <<EOF | kubectl apply -n sparrow-test -f -
              apiVersion: v1
              kind: Secret
              metadata:
              name: sparrow-api-secret
              stringData:
              WINDOWS_APP_SIGNATURE: "${{ secrets.WINDOWS_APP_SIGNATURE }}"
              WINDOWS_APP_URL: ""
              EOF
